FROM centos:7
ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*; \
rm -f /lib/systemd/system/anaconda.target.wants/*;
RUN yum install epel-release -y
RUN yum install net-tools -y
RUN rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
RUN yum-config-manager --add-repo  https://artifacts.elastic.co/packages/7.x/yum
RUN yum-config-manager --enable *
RUN yum install metricbeat* -y
RUN yum install filebeat -y
COPY conf/metricbeat.yml /etc/metricbeat/metricbeat.yml
COPY conf/filebeat.yml /etc/filebeat/filebeat.yml
RUN systemctl enable metricbeat.service
RUN systemctl enable filebeat.service
VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]
