version: "2.2"
services:
    es01:
        container_name: es01
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es02,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - es-net
        ports:
            - 9200:9200
        volumes:
            - data01:/usr/share/elasticsearch/data

    es02:
        container_name: es02
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
        environment: 
            - node.name=es02
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - es-net
        volumes:
            - data02:/usr/share/elasticsearch/data

    es03:
        container_name: es03
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
        environment: 
            - node.name=es03
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es02
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - es-net
        volumes:
            - data03:/usr/share/elasticsearch/data

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.14.0
        environment:
            SERVER_NAME: localhost
            ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
        networks:
            - es-net
        depends_on:
            - es01,es02,es03
        ports:
            - 5601:5601
        volumes:
            - data04:/usr/share/kibana

volumes:
    data01:
        driver: local
    data02:
        driver: local
    data03:
        driver: local
    data04:
        driver: local

networks:
    es-net:
      driver: bridge
